### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by 2601705041** [River-Zhang/SIFU#15]
Traceback (most recent call last):
  File "/home/j222/anaconda/envs/sifu/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/j222/anaconda/envs/sifu/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/j222/SIFU-main/apps/train.py", line 18, in <module>
    from lib.dataset.PIFuDataModule import PIFuDataModule
  File "/home/j222/SIFU-main/lib/dataset/PIFuDataModule.py", line 3, in <module>
    from .PIFuDataset import PIFuDataset
  File "/home/j222/SIFU-main/lib/dataset/PIFuDataset.py", line 31, in <module>
    import vedo
  File "/home/j222/anaconda/envs/sifu/lib/python3.8/site-packages/vedo/__init__.py", line 31, in <module>
    from vedo.plotter import *
  File "/home/j222/anaconda/envs/sifu/lib/python3.8/site-packages/vedo/plotter.py", line 4, in <module>
    import vtk
  File "/home/j222/anaconda/envs/sifu/lib/python3.8/site-packages/vtk.py", line 47, in <module>
    from vtkmodules.vtkIOXdmf2 import *
ImportError: /home/j222/anaconda/envs/sifu/lib/python3.8/site-packages/vtkmodules/../../.././././libcurl.so.4: undefined symbol: nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation

**Comment by River-Zhang** [comment]
It seems that this might be caused by the wrong environment. Could you please show me your environment settings?
