### ISSUE TITLE
AttributeError: 'pymeshlab.pmeshlab.MeshSet' object has no attribute 'laplacian_smooth'

### ISSUE THREAD

**Issue by CHMimilanlan** [River-Zhang/SIFU#43]
Since i am new in 3D generation, this problem has troubled me for whole day.
I install a lower version of pymeshlab, and it didn't fix the problem.
I asked GPT for answer, and try to change the code "ms.laplacian_smooth()" to "ms.apply_filter('laplacian_smooth', stepsmoothnum=10)", it didn't fix the problem too, bringing a new problem "pymeshlab.pmeshlab.PyMeshLabException: Failed to apply filter: laplacian_smooth. Filter does not exists. Take a look at MeshSet.print_filter_list function."

After a whole day try without any success, I turn to seek your help, I will be greatful for your timely response. Below is my output of running code "python -m apps.infer -cfg ./configs/sifu.yaml -gpu 0 -in_dir ./examples -out_dir ./results -loop_smpl 100 -loop_cloth 200 -hps_type pixie":

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1726817259.906534  325916 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1726817259.987223  328113 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 550.78), renderer: NVIDIA RTX A6000/PCIe/SSE2
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
W0000 00:00:1726817260.375936  328050 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1726817261.007470  328061 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1726817261.035935  328087 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1726817261.041428  328086 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1726817261.042100  328073 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1726817261.145889  328093 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1726817261.388064  328061 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1726817261.389568  328110 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1726817261.617627  328098 landmark_projection_calculator.cc:186] Using NORM_RECT without IMAGE_DIMENSIONS is only supported for the square ROI. Provide IMAGE_DIMENSIONS or use PROJECTION_MATRIX.
Body Fitting --- normal: 0.105 | silhouette: 0.054 | Total: 0.159: 100%|█████████████████████████████████████████████████████████████| 100/100 [00:17<00:00,  5.80it/s]
obj_path:./results/sifu/obj/2adf7e94e9c4dd987007a6661422c452_recon.obj%|█████████████████████████████████████████████████████████████| 100/100 [00:17<00:00,  6.46it/s]
2adf7e94e9c4dd987007a6661422c452:   0%|                                                                                                          | 0/5 [01:32<?, ?it/s]
Traceback (most recent call last):
  File "/data/xch/tools/anaconda/envs/chm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/xch/tools/anaconda/envs/chm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xch/chm_work_sapce/SIFU/apps/infer.py", line 515, in <module>
    verts_refine, faces_refine = remesh(
  File "/home/xch/chm_work_sapce/SIFU/lib/dataset/mesh_util.py", line 185, in remesh
    ms.laplacian_smooth()
AttributeError: 'pymeshlab.pmeshlab.MeshSet' object has no attribute 'laplacian_smooth'

**Comment by BeomjunGoo** [comment]
Did you try version 0.2.1? This worked for me.

**Comment by CHMimilanlan** [comment]
> Did you try version 0.2.1? This worked for me.

Thanks! It work!

**Comment by sebastianopazo1** [comment]
Hi @CHMimilanlan, how did you install pymeshlab 0.2.1 version? I'm can't do it.
Thanks for the help

**Comment by CHMimilanlan** [comment]
> Hi @CHMimilanlan, how did you install pymeshlab 0.2.1 version? I'm can't do it. Thanks for the help

Just pip install can work.
pip install pymeshlab==0.2.1
